const DATA = [
  {
    title: "Ejecutivo de atracción de talento",
    title2: "Ejecutivo de atracción de talento PERU",
    salary1: 9000,
    salary2: 11000,
    enterprise: "Grupo Salinas",
    country: "PERU",
  },
  {
    title: "Analista de reclutamiento zona Alvaro Obregon",
    title2: "Analista de reclutamiento zona COLOMBIA",
    salary1: 9000,
    salary2: 11000,
    enterprise: "Grupo Salinas",
    country: "COLOMBIA",
  },
  {
    title: "RECLUTADOR (A)",
    title2: "RECLUTADOR (A) CHILE",
    salary1: 2000,
    salary2: 3000,
    enterprise: " Grupo Inmobiliario Alhel",
    country: "CHILE",
  },
  {
    title: "Reclutador Zona Mixcoac",
    title2: "Reclutador Zona Mixcoac",
    salary1: 9000,
    salary2: 11000,
    enterprise: "Grupo Salinas",
    country: "MEXICO",
  },
  {
    title: "ANALISTA DE RECLUTAMIENTO ZONA ALVARO OBREGON",
    title2: "ANALISTA DE RECLUTAMIENTO ZONA COLOMBIA",
    salary1: 9000,
    salary2: 11000,
    enterprise: "Grupo Salinas",
    country: "COLOMBIA",
  },
  {
    title: "Ejecutivo de atracción de talento",
    title2: "Ejecutivo de atracción de talento PERU",
    salary1: 9000,
    salary2: 11000,
    enterprise: "Grupo Salinas",
    country: "PERU",
  },
  {
    title: "Analista de reclutamiento zona Alvaro Obregon",
    title2: "Analista de reclutamiento zona PERU",
    salary1: 9000,
    salary2: 11000,
    enterprise: "Grupo Salinas",
    country: "PERU",
  },
  {
    title: "RECLUTADOR (A)",
    title2: "RECLUTADOR (A) COLOMBIA",
    salary1: 2000,
    salary2: 3000,
    enterprise: " Grupo Inmobiliario Alhel",
    country: "COLOMBIA",
  },
  {
    title: "Reclutador Zona COLOMBIA",
    title2: "Reclutador Zona CHILE",
    salary1: 12000,
    salary2: 13000,
    enterprise: "Grupo Salinas",
    country: "CHILE",
  },
  {
    title: "ANALISTA DE RECLUTAMIENTO ZONA ALVARO OBREGON",
    title2: "ANALISTA DE RECLUTAMIENTO ZONA ALVARO CHILE",
    salary1: 12000,
    salary2: 14000,
    enterprise: "Grupo Salinas",
    country: "CHILE",
  },
  {
    title: "Ejecutivo de atracción de talento",
    title2: "Ejecutivo de atracción de talento PERU",
    salary1: 4000,
    salary2: 6000,
    enterprise: "Grupo Salinas",
    country: "PERU",
  },
  {
    title: "Analista de reclutamiento zona CHILE",
    title2: "Analista de reclutamiento zona MEXICO",
    salary1: 2000,
    salary2: 3000,
    enterprise: "Grupo Salinas",
    country: "MEXICO",
  },
  {
    title: "RECLUTADOR (A)",
    title2: "RECLUTADOR (A) CHILE",
    salary1: 2000,
    salary2: 3000,
    enterprise: "Grupo Inmobiliario Alhel",
    country: "CHILE",
  },
  {
    title: "Reclutador Zona Mixcoac",
    title2: "Reclutador Zona MEXICO",
    salary1: 1000,
    salary2: 2000,
    enterprise: "Grupo Salinas",
    country: "MEXICO",
  },
  {
    title: "ANALISTA DE RECLUTAMIENTO ZONA ALVARO OBREGON",
    title2: "ANALISTA DE RECLUTAMIENTO ZONA PERU",
    salary1: 12000,
    salary2: 14000,
    enterprise: "Grupo Salinas",
    country: "PERU",
  },
  {
    title: "Ejecutivo de atracción de talento",
    title2: "Ejecutivo de atracción de talento COLOMBIA",
    salary1: 9000,
    salary2: 11000,
    enterprise: "Grupo Salinas",
    country: "COLOMBIA",
  },
  {
    title: "Analista de reclutamiento zona Alvaro Obregon",
    title2: "Analista de reclutamiento zona MEXICO",
    salary1: 9000,
    salary2: 11000,
    enterprise: "Grupo Salinas",
    country: "MEXICO",
  },
  {
    title: "RECLUTADOR (A) COLOMBIA",
    title2: "RECLUTADOR (A) COLOMBIA",
    salary1: 9000,
    salary2: 11000,
    enterprise: "Grupo Inmobiliario Alhel",
    country: "COLOMBIA",
  },
  {
    title: "Reclutador Zona PERU",
    title2: "Reclutador Zona Mixcoac",
    salary1: 9000,
    salary2: 11000,
    enterprise: "Grupo Salinas",
    country: "PERU",
  },
  {
    title: "ANALISTA DE RECLUTAMIENTO ZONA ALVARO CHILE",
    title2: "ANALISTA DE PLANILLA",
    salary1: 9000,
    salary2: 11000,
    enterprise: "Grupo Salinas",
    country: "CHILE",
  },
  {
    title: "Ejecutivo de atracción de talento",
    title2: "Ejecutivo de rrhh",
    salary1: 9000,
    salary2: 11000,
    enterprise: "Grupo Salinas",
    country: "ECUADOR",
  },
  {
    title: "Analista de reclutamiento zona Alvaro Obregon",
    title2: "Analista de rotativo zona Alvaro Obregon",
    salary1: 9000,
    salary2: 11000,
    enterprise: "Grupo Salinas",
    country: "ECUADOR",
  },
  {
    title: "RECLUTADOR (A)",
    title2: "RECLUTADOR (A) PERU",
    salary1: 9000,
    salary2: 11000,
    enterprise: "Grupo Inmobiliario Alhel",
    country: "PERU",
  },
  {
    title: "Reclutador Zona Mixcoac",
    title2: "Reclutador Zona Mixcoac",
    salary1: 9000,
    salary2: 11000,
    enterprise: "Grupo Nuevo",
    country: "ARGENTINA",
  },
  {
    title: "ANALISTA DE RECLUTAMIENTO ZONA ALVARO COLOMBIA",
    title2: "ANALISTA DE RECLUTAMIENTO ZONA ALVARO OBREGON",
    salary1: 9000,
    salary2: 11000,
    enterprise: "Grupo Salinas",
    country: "COLOMBIA",
  },
];

export default DATA;
